### ISSUE TITLE
Dataset please

### ISSUE THREAD

**Issue by abangani88** [jatin-mishra/MerchantRatingSystem#1]
@jatin-mishra 
It's urgent.
Please provide the dataset.

**Comment by jatin-mishra** [comment]
1. @abangani88 
sorry for your inconvenience, but i dont think i have this dataset now...

**Comment by abangani88** [comment]
Requesting you to please check once again and if possible provide me the datasets as I want urgently.
If you want, I can pay you also.

**Comment by jatin-mishra** [comment]
As per your request, I tried to get it from other sources, but as it was
mentioned in their
email i cann't share this.. but i can share legal procedure that you should
follow to get this dataset..
plz share your any email id so that i can send this procedure privately..
